### ISSUE TITLE
my mouse works but the cheat doesnt

### ISSUE THREAD

**Issue by doiseffe** [reezliabi/aerduino-valorant-cheat#10]
so, as i wrote above, my mouse moves with doge library, but also when i config the file ''config.ini'' the cheat doesnt work

**Comment by Yutooop** [comment]
its because this source is trash!

**Comment by reezliabi** [comment]
„its because this source is trash!“

just because you cant paste a p2c doesn't mean the source is bad :)
Learn how to code retard and you'll have it easier to make your cheat. Also this Source is ready to use, python code works like a charm. The only thing which you probably need to update is the arduino code.

**Comment by Yutooop** [comment]
lol have you seen that long code you wrote? tell me again its a good source? 

I would never need a source like this whut.  

What kind of logic is "just because you cant paste a p2c doesn't mean the source is bad :)
Learn how to code retard and you'll have it easier to make your cheat" ?????????????

haha mate please learn to properly code..... Calling me a "Retard" shows me how small minded you really are. Why do you instantly think people don't know how to code when they call you out? Are you afraid? I don't understand. 

I hope you have a nice day.

**Comment by Yutooop** [comment]
Grow up kid!

**Comment by Yutooop** [comment]
hahah no you closed this ticket so people dont see it.....What a kid.

**Comment by Yutooop** [comment]
I just reported you to the GitHub team by the way for what you said so nicely here!
